"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from documenso_sdk.models import DocumensoError
from documenso_sdk.types import BaseModel
import httpx
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, TypedDict


class DocumentDuplicateDocumentRequestTypedDict(TypedDict):
    document_id: float


class DocumentDuplicateDocumentRequest(BaseModel):
    document_id: Annotated[float, pydantic.Field(alias="documentId")]


class DocumentDuplicateDocumentInternalServerErrorIssueTypedDict(TypedDict):
    message: str


class DocumentDuplicateDocumentInternalServerErrorIssue(BaseModel):
    message: str


class DocumentDuplicateDocumentInternalServerErrorData(BaseModel):
    message: str

    code: str

    issues: Optional[List[DocumentDuplicateDocumentInternalServerErrorIssue]] = None


class DocumentDuplicateDocumentInternalServerError(DocumensoError):
    r"""Internal server error"""

    data: DocumentDuplicateDocumentInternalServerErrorData

    def __init__(
        self,
        data: DocumentDuplicateDocumentInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class DocumentDuplicateDocumentBadRequestIssueTypedDict(TypedDict):
    message: str


class DocumentDuplicateDocumentBadRequestIssue(BaseModel):
    message: str


class DocumentDuplicateDocumentBadRequestErrorData(BaseModel):
    message: str

    code: str

    issues: Optional[List[DocumentDuplicateDocumentBadRequestIssue]] = None


class DocumentDuplicateDocumentBadRequestError(DocumensoError):
    r"""Invalid input data"""

    data: DocumentDuplicateDocumentBadRequestErrorData

    def __init__(
        self,
        data: DocumentDuplicateDocumentBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class DocumentDuplicateDocumentResponseTypedDict(TypedDict):
    r"""Successful response"""

    document_id: float


class DocumentDuplicateDocumentResponse(BaseModel):
    r"""Successful response"""

    document_id: Annotated[float, pydantic.Field(alias="documentId")]
