"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from documenso_sdk.models import DocumensoError
from documenso_sdk.types import BaseModel, UNSET_SENTINEL
import httpx
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class EnvelopeCancelRequestTypedDict(TypedDict):
    envelope_id: str
    reason: NotRequired[str]


class EnvelopeCancelRequest(BaseModel):
    envelope_id: Annotated[str, pydantic.Field(alias="envelopeId")]

    reason: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["reason"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class EnvelopeCancelInternalServerErrorIssueTypedDict(TypedDict):
    message: str


class EnvelopeCancelInternalServerErrorIssue(BaseModel):
    message: str


class EnvelopeCancelInternalServerErrorData(BaseModel):
    message: str
    code: str
    issues: Optional[List[EnvelopeCancelInternalServerErrorIssue]] = None


@dataclass(unsafe_hash=True)
class EnvelopeCancelInternalServerError(DocumensoError):
    r"""Internal server error"""

    data: EnvelopeCancelInternalServerErrorData = field(hash=False)

    def __init__(
        self,
        data: EnvelopeCancelInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class EnvelopeCancelForbiddenIssueTypedDict(TypedDict):
    message: str


class EnvelopeCancelForbiddenIssue(BaseModel):
    message: str


class EnvelopeCancelForbiddenErrorData(BaseModel):
    message: str
    code: str
    issues: Optional[List[EnvelopeCancelForbiddenIssue]] = None


@dataclass(unsafe_hash=True)
class EnvelopeCancelForbiddenError(DocumensoError):
    r"""Insufficient access"""

    data: EnvelopeCancelForbiddenErrorData = field(hash=False)

    def __init__(
        self,
        data: EnvelopeCancelForbiddenErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class EnvelopeCancelUnauthorizedIssueTypedDict(TypedDict):
    message: str


class EnvelopeCancelUnauthorizedIssue(BaseModel):
    message: str


class EnvelopeCancelUnauthorizedErrorData(BaseModel):
    message: str
    code: str
    issues: Optional[List[EnvelopeCancelUnauthorizedIssue]] = None


@dataclass(unsafe_hash=True)
class EnvelopeCancelUnauthorizedError(DocumensoError):
    r"""Authorization not provided"""

    data: EnvelopeCancelUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: EnvelopeCancelUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class EnvelopeCancelBadRequestIssueTypedDict(TypedDict):
    message: str


class EnvelopeCancelBadRequestIssue(BaseModel):
    message: str


class EnvelopeCancelBadRequestErrorData(BaseModel):
    message: str
    code: str
    issues: Optional[List[EnvelopeCancelBadRequestIssue]] = None


@dataclass(unsafe_hash=True)
class EnvelopeCancelBadRequestError(DocumensoError):
    r"""Invalid input data"""

    data: EnvelopeCancelBadRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: EnvelopeCancelBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class EnvelopeCancelResponseTypedDict(TypedDict):
    r"""Successful response"""

    success: bool


class EnvelopeCancelResponse(BaseModel):
    r"""Successful response"""

    success: bool


try:
    EnvelopeCancelRequest.model_rebuild()
except NameError:
    pass
