"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from documenso_sdk.models import DocumensoError
from documenso_sdk.types import BaseModel
from documenso_sdk.utils import FieldMetadata, PathParamMetadata
import httpx
import pydantic
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, TypedDict


class EnvelopeAuditLogDownloadPdfRequestTypedDict(TypedDict):
    envelope_id: str
    r"""The ID of the envelope to download the audit log for."""


class EnvelopeAuditLogDownloadPdfRequest(BaseModel):
    envelope_id: Annotated[
        str,
        pydantic.Field(alias="envelopeId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The ID of the envelope to download the audit log for."""


class EnvelopeAuditLogDownloadPdfInternalServerErrorIssueTypedDict(TypedDict):
    message: str


class EnvelopeAuditLogDownloadPdfInternalServerErrorIssue(BaseModel):
    message: str


class EnvelopeAuditLogDownloadPdfInternalServerErrorData(BaseModel):
    message: str
    code: str
    issues: Optional[List[EnvelopeAuditLogDownloadPdfInternalServerErrorIssue]] = None


@dataclass(unsafe_hash=True)
class EnvelopeAuditLogDownloadPdfInternalServerError(DocumensoError):
    r"""Internal server error"""

    data: EnvelopeAuditLogDownloadPdfInternalServerErrorData = field(hash=False)

    def __init__(
        self,
        data: EnvelopeAuditLogDownloadPdfInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class EnvelopeAuditLogDownloadPdfNotFoundIssueTypedDict(TypedDict):
    message: str


class EnvelopeAuditLogDownloadPdfNotFoundIssue(BaseModel):
    message: str


class EnvelopeAuditLogDownloadPdfNotFoundErrorData(BaseModel):
    message: str
    code: str
    issues: Optional[List[EnvelopeAuditLogDownloadPdfNotFoundIssue]] = None


@dataclass(unsafe_hash=True)
class EnvelopeAuditLogDownloadPdfNotFoundError(DocumensoError):
    r"""Not found"""

    data: EnvelopeAuditLogDownloadPdfNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: EnvelopeAuditLogDownloadPdfNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class EnvelopeAuditLogDownloadPdfForbiddenIssueTypedDict(TypedDict):
    message: str


class EnvelopeAuditLogDownloadPdfForbiddenIssue(BaseModel):
    message: str


class EnvelopeAuditLogDownloadPdfForbiddenErrorData(BaseModel):
    message: str
    code: str
    issues: Optional[List[EnvelopeAuditLogDownloadPdfForbiddenIssue]] = None


@dataclass(unsafe_hash=True)
class EnvelopeAuditLogDownloadPdfForbiddenError(DocumensoError):
    r"""Insufficient access"""

    data: EnvelopeAuditLogDownloadPdfForbiddenErrorData = field(hash=False)

    def __init__(
        self,
        data: EnvelopeAuditLogDownloadPdfForbiddenErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class EnvelopeAuditLogDownloadPdfUnauthorizedIssueTypedDict(TypedDict):
    message: str


class EnvelopeAuditLogDownloadPdfUnauthorizedIssue(BaseModel):
    message: str


class EnvelopeAuditLogDownloadPdfUnauthorizedErrorData(BaseModel):
    message: str
    code: str
    issues: Optional[List[EnvelopeAuditLogDownloadPdfUnauthorizedIssue]] = None


@dataclass(unsafe_hash=True)
class EnvelopeAuditLogDownloadPdfUnauthorizedError(DocumensoError):
    r"""Authorization not provided"""

    data: EnvelopeAuditLogDownloadPdfUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: EnvelopeAuditLogDownloadPdfUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class EnvelopeAuditLogDownloadPdfBadRequestIssueTypedDict(TypedDict):
    message: str


class EnvelopeAuditLogDownloadPdfBadRequestIssue(BaseModel):
    message: str


class EnvelopeAuditLogDownloadPdfBadRequestErrorData(BaseModel):
    message: str
    code: str
    issues: Optional[List[EnvelopeAuditLogDownloadPdfBadRequestIssue]] = None


@dataclass(unsafe_hash=True)
class EnvelopeAuditLogDownloadPdfBadRequestError(DocumensoError):
    r"""Invalid input data"""

    data: EnvelopeAuditLogDownloadPdfBadRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: EnvelopeAuditLogDownloadPdfBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class EnvelopeAuditLogDownloadPdfResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: Any


class EnvelopeAuditLogDownloadPdfResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: Any
