"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from documenso_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class TemplateToggleTemplateDirectLinkRequestBodyTypedDict(TypedDict):
    template_id: float
    enabled: bool


class TemplateToggleTemplateDirectLinkRequestBody(BaseModel):
    template_id: Annotated[float, pydantic.Field(alias="templateId")]

    enabled: bool


class TemplateToggleTemplateDirectLinkResponseBodyTypedDict(TypedDict):
    r"""Successful response"""

    id: str
    template_id: int
    token: str
    created_at: str
    enabled: bool
    direct_template_recipient_id: int


class TemplateToggleTemplateDirectLinkResponseBody(BaseModel):
    r"""Successful response"""

    id: str

    template_id: Annotated[int, pydantic.Field(alias="templateId")]

    token: str

    created_at: Annotated[str, pydantic.Field(alias="createdAt")]

    enabled: bool

    direct_template_recipient_id: Annotated[
        int, pydantic.Field(alias="directTemplateRecipientId")
    ]
