workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    documenso-OAS:
        inputs:
            - location: registry.speakeasyapi.dev/documenso-inc/api/documenso-v-2-beta-api:main
        registry:
            location: registry.speakeasyapi.dev/documenso-inc/api/documenso-oas
targets:
    documenso:
        target: python
        source: documenso-OAS
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/documenso-inc/api/documenso-oas-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
